name: Publicar Contenido Diario - 4 Veces

on:
  schedule:
    # Publicación 1: 9:00 AM UTC (11:00 AM España)
    - cron: '0 9 * * *'
    # Publicación 2: 12:00 PM UTC (2:00 PM España)  
    - cron: '0 12 * * *'
    # Publicación 3: 3:00 PM UTC (5:00 PM España)
    - cron: '0 15 * * *'
    # Publicación 4: 6:00 PM UTC (8:00 PM España)
    - cron: '0 18 * * *'
  workflow_dispatch:
    inputs:
      publicacion_numero:
        description: 'Número de publicación (0-3)'
        required: true
        default: '0'
        type: choice
        options:
        - '0'
        - '1' 
        - '2'
        - '3'

jobs:
  publicar:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Mapeo de horarios a números de publicación
        include:
          - cron: '0 9 * * *'
            pub_num: 0
          - cron: '0 12 * * *'
            pub_num: 1
          - cron: '0 15 * * *' 
            pub_num: 2
          - cron: '0 18 * * *'
            pub_num: 3
    
    # Solo ejecutar el job que coincide con el cron actual
    if: github.event.schedule == matrix.cron || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install twitter-api-v2 node-fetch

      - name: Determinar número de publicación
        id: pub_num
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "PUB_NUM=${{ github.event.inputs.publicacion_numero }}" >> $GITHUB_ENV
          else
            echo "PUB_NUM=${{ matrix.pub_num }}" >> $GITHUB_ENV
          fi
          echo "Ejecutando publicación número: $PUB_NUM"

      - name: Ejecutar publicación específica
        run: node bot.js $PUB_NUM
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
          TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
